version: "3.8"

# Run locally using this instead:
# docker run --name some-postgres -e POSTGRES_PASSWORD=password -e POSTGRES_USER=user -e POSTGRES_DB=app -p 5432:5432 -d postgres


services:
  app:
    build:
      context: .
    ports:
      - "8080:8080" # http://localhost:8080
    links:
      - db:db
  db:
    image: postgres:16
    ports:
      - "127.0.0.1:5432:5432"
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=app
