POST http://localhost:8080/admin/config
Content-Type: application/json
Authorization: Bearer very-very-secret-admin-token

[{
  "id": "a3",
  "orgMatchers": [
    {
      "matcher": ".*",
      "repoMatchers": [
        {
          "matcher": "my-team-.*",
          "branchMatchers": [
            {
              "matcher": ".*"
            }
          ]
        },
        {
          "matcher": "(TEAM|team)-.*"
        }
      ]
    }
  ]
}]

### Get all dashboard configs

GET http://localhost:8080/admin/config
Authorization: Bearer very-very-secret-admin-token

### Get a specific dashboard config

GET http://localhost:8080/admin/config?dashboardConfigId=a3
Authorization: Bearer very-very-secret-admin-token
